---

- name: Run whoami on remote-machine1
  hosts: remote-machine1
  tasks:
  - name: Install Git
    command: 'whoami'
    register: result
  - debug: msg={{ result.stdout }}
  
- name: Install apache on remote-machine2
  hosts: remote-machine2
  become: yes
  become_method: su
  become_user: root
  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: present

